In [2]:
"""构建一个没有任何参数的自定义层"""
import torch
import torch.nn.functional as F
from torch import nn

class CenterLayer(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, X):
    return X - X.mean()

layer =  CenterLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
"""将层作为组件合并到构建更复杂的模型中"""
net = nn.Sequential(nn.Linear(8, 128), CenterLayer())

Y = net(torch.rand(4, 8)) ## torch.rand符合均匀分布[0,1]
Y.mean()

tensor(2.7940e-09, grad_fn=<MeanBackward0>)

In [15]:
"""带参数的图层"""
class MyLinear(nn.Module):
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units)) ## torch.randn符合正态分布[0,1]
    self.bias = nn.Parameter(torch.randn(units, ))

  def forward(self, X):
    linear = torch.matmul(X, self.weight.data) + self.bias.data
    return F.relu(linear)

dense = MyLinear(5, 3) ## 只是进行了初始化，调用forward函数
dense.weight

Parameter containing:
tensor([[-0.0931,  1.3423, -1.9284],
        [ 0.5786, -0.0748, -0.0039],
        [ 2.0042,  0.1722, -0.0890],
        [-1.3341, -0.4915, -1.2662],
        [ 0.5106,  0.0814,  1.5259]], requires_grad=True)

In [16]:
"""使用自定义层直接执行正向传播计算"""
dense(torch.rand(2,5))

tensor([[1.9410, 2.1140, 0.7889],
        [0.0000, 1.6737, 0.0000]])

In [17]:
"""使用自定义层构建模块"""
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [1.9819]])