### 二维最大池化
> * 返回滑动窗口中的最大值
### 填充，步幅和多个通道
> * 池化层和卷积层类似，都具有填充和步幅
> * 没有可学习的参数
> * 在每个输入通道应用池化层以获得相对应的输出通道
> * 输出通道数=输入通道数
### 平均池化层
> * 最大池化层：每个窗口中最强的模式信号
> * 平均池化层：将最大池化层中的“最大”操作替换为“平均”
### 总结
> * 池化层返回窗口中的最大或平均值
> * 缓解卷积层对位置的敏感性
> * 同样有窗口大小、填充和步幅作为超参数

<font color='red'>在池化层后不需要添加激活函数，因为池化本身就是非线性的，并不需要激活函数来添加非线性</font>
<font color='red'>池化层的默认步长是kernel_size，所以步长为1需要说明</font>

In [1]:
import torch
from torch import nn
from d2l import limutorch as d2l

"""实现池化层的正向传播"""
def pool2d(X, pool_szie, mode='max'):
    p_h, p_w = pool_szie
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
    return Y

In [3]:
"""验证二维最大池化层的输出"""
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [4]:
"""验证平均池化"""
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [20]:
"""填充和步幅"""
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [10]:
"""深度学习框架中的步幅和最大池化窗口的大小相同"""
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [11]:
"""填充和步幅也可以手动设定"""
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [12]:
"""设定一个任意大小的矩形池化窗口，并分别设定填充和步幅的高度和宽度"""
pool2d = nn.MaxPool2d((2, 3), padding=(1, 1), stride=(2, 3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [21]:
"""池化层在每个输入通道上单独运算"""
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [22]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])