In [2]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
len(x),x.shape

(4, torch.Size([4]))

In [5]:
A = torch.arange(20).reshape((5,4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

<font color='orange'>矩阵的转置</font>

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, B, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [9]:
A * B ##两个矩阵的按元素乘法，称为哈达玛积，并非矩阵乘法

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [10]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a + X, a*X, (a*X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [11]:
x = torch.arange(4,dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [12]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2,5,4)
A, A.shape,A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor(780.))

In [13]:
A_sum_axis0 = A.sum(axis=0) ## axis=0,1,2代表reshape(x,y,z)中的x,y,z求和
A_sum_axis0,A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [14]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [15]:
A.sum(axis=[0,1])

tensor([180., 190., 200., 210.])

In [16]:
A.mean(), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [17]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

<font color='orange'> Keepdims=True在计算总和和均值时保持轴数不变这里就会将原来的[2,5,4]变为[2,1,4]</font>

In [18]:
sum_A = A.sum(axis=1, keepdims=True) ## Keepdims=True在计算总和和均值时保持轴数不变这里就会将原来的[2,5,4]变为[2,1,4]
sum_A, sum_A.shape

(tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]]),
 torch.Size([2, 1, 4]))

In [19]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

<font color='orange'>cumsum是累加求和的意思</font>

In [20]:
A.cumsum(axis=1) ## cumsum是累加求和的意思

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

* <font color='orange'>torch.dot表示的向量之间的点积，仅仅适用于两边都是一维数据</font>
* <font color='orange'>torch.mv表示的矩阵和向量之间的点积，左边为$m*n$的数据，右边需要为$n*1$的数据</font>
* <font color='orange'>torch.mm表示矩阵和矩阵之间的点积，也就是真正意义上的矩阵乘法</font>

In [2]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x,y) ## dot是进行点积操作，点积是相同位置的按元素乘积的和

(tensor([[0, 1],
         [2, 3]]),
 tensor([[0, 1],
         [2, 3]]))

In [22]:
torch.sum(x*y) ## 点积可以通过先按元素乘法，在进行求和来表示两个向量的点积

tensor(6.)

In [23]:
A = torch.arange(4, dtype=torch.float32).reshape(1,4)
A.shape, x.shape,torch.mv(A,x)

(torch.Size([1, 4]), torch.Size([4]), tensor([14.]))

In [24]:
m = torch.arange(6).reshape(3,2)
n = torch.arange(6).reshape(2,3)
torch.mm(m,n)

tensor([[ 3,  4,  5],
        [ 9, 14, 19],
        [15, 24, 33]])

<font color='orange'>torch.norm()表示向量或矩阵的范数，及所有元素平方和的开根号</font>

In [25]:
u = torch.tensor([[3.0,-4.0]])
A = torch.arange(20,dtype=torch.float32).reshape(2,2,5)
u, A, torch.norm(u),torch.norm(A)

(tensor([[ 3., -4.]]),
 tensor([[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.]],
 
         [[10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.]]]),
 tensor(5.),
 tensor(49.6991))

In [26]:
u, torch.abs(u).sum() ## abs是绝对值的意思

(tensor([[ 3., -4.]]), tensor(7.))

$\partial$

In [27]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [30]:
x.requires_grad_(True)
x.grad

In [37]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

通过利用反向传播函数来自动计算y关于x每个分量的梯度

In [38]:
y.backward() ## 这里y=2*x*x
x.grad

tensor([ 1.,  5.,  9., 13.])

In [33]:
x.grad == 4 * x

tensor([True, True, True, True])

In [36]:
# 在默认情况下，pytorch会累积梯度，所以需要清楚之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [39]:
x.grad.zero_()
y = x * x
y.sum().backward() ## 因为这里的y是标量，所以需要y.sum()进行求导
x.grad

tensor([0., 2., 4., 6.])

In [42]:
x.grad.zero_()
y = x * x
u =  y.detach() ## 这里相当于将y变为一个关于x的常量，常数，赋值给u
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [43]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [47]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a, d, a.grad, a.grad == d/a

(tensor(-1.3753, requires_grad=True),
 tensor(-140826.0781, grad_fn=<MulBackward0>),
 tensor(102400.),
 tensor(True))